apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  #name: "keptn-crossplane"
  name: keptn-dellpages
  spec:
    stages:
      - name: "perf-test"
        sequences:
          - name: "delivery"
            tasks:
              #- name: "environment-setup"
              #  properties:
              #    size: "medium"
              #- name: "monitoring-setup"
              - name: "deployment"
                properties:
                  #deploymentstrategy: "user_managed"
                  deploymentstrategy: "direct"
              - name: "test"
                properties:
                  teststrategy: "performance"
              - name: "evaluation"
      #- name: "release"
      # - name: "environment-teardown"
      - name: "production"
        sequences:
          - name: "delivery"
            triggeredOn:
              - event: "perf-test.delivery.finished"
            tasks:
              - name: "deployment"
                properties:
                  deploymentstrategy: "direct"
              - name: "release"
